### ISSUE TITLE
I’m not sure what Markbot wants

### ISSUE THREAD

**Issue by Riv67** [Riv67/kraken-good-accessibility#2]
@hellachella @JessJodoin

Markbot is saying that line 90 has a unexpected leading of zero, I didn’t change anything to that line and I’m not sure what to fix. Any idea what the problem is?

![Screen Shot 2020-10-02 at 1 55 05 PM](https://user-images.githubusercontent.com/55094177/94954439-2323b100-04b7-11eb-93f0-63c4abfa74d1.png)
![Screen Shot 2020-10-02 at 1 55 11 PM](https://user-images.githubusercontent.com/55094177/94954442-2454de00-04b7-11eb-9422-6268ad911f0f.png)

**Comment by JessJodoin** [comment]
Remove the 0 in front of `padding: 0.5rem;` and make it `padding: .5rem;`

**Comment by Riv67** [comment]
Ahh thanks!
